env:
  # name or (venv) path of python executable
  python_bin: python3
  # argumtnst passing to (attached to) the python bin
  python_args: []
  # filename of batch job information
  job_file: batch_job.yaml
  # use de-dup feature to reduce file length, Default: False
  yqml_reference: True
jobs:
  # name for the job, use whatever you want
  lstm:
    # what to execute
    script: Keras_LSTM_PTB.py
    # argumtnst passing to (attached to) the script, support following types:
    #   * -foo
    #   * [1, 2, 3]
    #   * -foo: [2, 4]
    #   * -foo: [[1, 2, 3], [10, 20]]
    # warning: space is not supported yet (escape by "'str w/ space'")
    args:
      - -t
      - --step: [15, 30, 45]
      - --batch: [10, 20, 30]
      - --embd: [200, 500, 800]
      - --lstm2: [100, 300, 500]
    # how many times through this job
    loop: 3
    # check if all the training logs/output (filename Only) are present
    check:
      # '15_10_200_100_2020-11-30 13:26:10.csv'
      #   ==> ['15', '10', '200', '100']
      filename: '^(\d+)_(\d+)_(\d+)_(\d+)_\d{4}.+.h5'
      # match arguments by "token",
      #   e.g. [1] will match [123] in ['--foo', 123, '--bar', 'xyz']
      match: [2, 4, 6, 8]
